#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm test
# npx lint-staged --allow-empty 
# npm run lint

# echo "Hello,world"
# npm run prettier:check
# npm run prettier:write && git add -A .
# npm run eslint:check
npm run eslint:fix

# npx lint-staged
# npx lint-staged --allow-empty $1
